--------------------------------------------------------
--  File created - Friday-December-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "SCARF"."CART" 
   (	"CUS_USERNAME" VARCHAR2(100 BYTE), 
	"PRODUCT_ID" NUMBER(11,0), 
	"CART_AMOUNT" NUMBER(11,0), 
	"PRODUCT_IMAGEPATH" VARCHAR2(300 BYTE), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"PRODUCT_DESCRIPTION" VARCHAR2(300 BYTE), 
	"PRODUCT_PRICE" FLOAT(126), 
	"CART_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCARF.CART
SET DEFINE OFF;
Insert into SCARF.CART (CUS_USERNAME,PRODUCT_ID,CART_AMOUNT,PRODUCT_IMAGEPATH,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRODUCT_PRICE,CART_ID) values ('ayesha2',5,1,null,'Square','Square Printed Coral',45,10);
Insert into SCARF.CART (CUS_USERNAME,PRODUCT_ID,CART_AMOUNT,PRODUCT_IMAGEPATH,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRODUCT_PRICE,CART_ID) values ('ayesha2',5,1,'upload/Square Printed 1.png','Square','Square Printed Coral',45,9);
Insert into SCARF.CART (CUS_USERNAME,PRODUCT_ID,CART_AMOUNT,PRODUCT_IMAGEPATH,PRODUCT_NAME,PRODUCT_DESCRIPTION,PRODUCT_PRICE,CART_ID) values ('ayesha2',5,3,null,'Square','Square Printed Coral',45,12);
--------------------------------------------------------
--  DDL for Index CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCARF"."CART_PK" ON "SCARF"."CART" ("CART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SCARF"."CART" ADD CONSTRAINT "CART_PK" PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCARF"."CART" MODIFY ("CART_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger CART_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCARF"."CART_TRG" 
BEFORE INSERT ON CART 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CART_ID IS NULL THEN
      SELECT CART_SEQ1.NEXTVAL INTO :NEW.CART_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCARF"."CART_TRG" ENABLE;
