--------------------------------------------------------
--  File created - Friday-December-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SCARF"."CUSTOMER" 
   (	"CUS_USERNAME" VARCHAR2(100 BYTE), 
	"CUS_PASSWORD" VARCHAR2(30 BYTE), 
	"CUS_REALNAME" VARCHAR2(100 BYTE), 
	"CUS_ADD" VARCHAR2(300 BYTE), 
	"CUS_EMAIL" VARCHAR2(100 BYTE), 
	"CUS_PHONE" VARCHAR2(11 BYTE), 
	"CUS_BIRTHDAY" DATE, 
	"CUS_GENDER" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCARF.CUSTOMER
SET DEFINE OFF;
Insert into SCARF.CUSTOMER (CUS_USERNAME,CUS_PASSWORD,CUS_REALNAME,CUS_ADD,CUS_EMAIL,CUS_PHONE,CUS_BIRTHDAY,CUS_GENDER) values ('ayesha2','1234','wan ayesha','Kota bBharu','ayesha@gmail.com','0147352948',to_date('16/08/2016','DD/MM/RRRR'),'Female');
Insert into SCARF.CUSTOMER (CUS_USERNAME,CUS_PASSWORD,CUS_REALNAME,CUS_ADD,CUS_EMAIL,CUS_PHONE,CUS_BIRTHDAY,CUS_GENDER) values ('farzana','1234','farzana','negeri sembilan','farzana@gmail.com','0147352948',to_date('04/06/1997','DD/MM/RRRR'),'Female');
Insert into SCARF.CUSTOMER (CUS_USERNAME,CUS_PASSWORD,CUS_REALNAME,CUS_ADD,CUS_EMAIL,CUS_PHONE,CUS_BIRTHDAY,CUS_GENDER) values ('ain','1234','nor''ain','melaka','ain@gmail.com','0199998877',to_date('01/01/1997','DD/MM/RRRR'),'Female');
Insert into SCARF.CUSTOMER (CUS_USERNAME,CUS_PASSWORD,CUS_REALNAME,CUS_ADD,CUS_EMAIL,CUS_PHONE,CUS_BIRTHDAY,CUS_GENDER) values ('coki','1234','coki','uitm','coki@gmail.com','0199998877',to_date('03/11/1997','DD/MM/RRRR'),'Male');
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCARF"."CUSTOMER_PK" ON "SCARF"."CUSTOMER" ("CUS_USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SCARF"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUS_USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCARF"."CUSTOMER" MODIFY ("CUS_USERNAME" NOT NULL ENABLE);
