--------------------------------------------------------
--  File created - Friday-December-13-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "SCARF"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER(11,0), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"PRODUCT_IMAGEPATH" VARCHAR2(300 BYTE), 
	"PRODUCT_PRICE" FLOAT(126), 
	"PRODUCT_TYPE" VARCHAR2(50 BYTE), 
	"PRODUCT_AMOUNT" NUMBER(11,0), 
	"PRODUCT_DESCRIPTION" VARCHAR2(300 BYTE), 
	"PRODUCT_SOLD" NUMBER(11,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SCARF.PRODUCT
SET DEFINE OFF;
Insert into SCARF.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_IMAGEPATH,PRODUCT_PRICE,PRODUCT_TYPE,PRODUCT_AMOUNT,PRODUCT_DESCRIPTION,PRODUCT_SOLD) values (5,'Square Printed Coral','upload/Square Printed 1.png',45,'Square Printed',null,'Square Printed Coral',null);
Insert into SCARF.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_IMAGEPATH,PRODUCT_PRICE,PRODUCT_TYPE,PRODUCT_AMOUNT,PRODUCT_DESCRIPTION,PRODUCT_SOLD) values (3,'Inner Neck (Black)','upload/Inner_neck_black.jpg',10,'Inner Neck',null,'Inner Neck (Black)',null);
Insert into SCARF.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_IMAGEPATH,PRODUCT_PRICE,PRODUCT_TYPE,PRODUCT_AMOUNT,PRODUCT_DESCRIPTION,PRODUCT_SOLD) values (6,'shawl bunga',null,20,'Satin Printed',null,'shawl bunga (black)',null);
Insert into SCARF.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_IMAGEPATH,PRODUCT_PRICE,PRODUCT_TYPE,PRODUCT_AMOUNT,PRODUCT_DESCRIPTION,PRODUCT_SOLD) values (7,'Inner Neck (Blue)',null,10,'Inner Neck',null,'jhhgvgvff',null);
Insert into SCARF.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRODUCT_IMAGEPATH,PRODUCT_PRICE,PRODUCT_TYPE,PRODUCT_AMOUNT,PRODUCT_DESCRIPTION,PRODUCT_SOLD) values (8,'shawl bunga',null,10,'Square Printed',null,'jhjhjhlj',null);
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCARF"."TABLE1_PK" ON "SCARF"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "SCARF"."PRODUCT" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCARF"."PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger PRODUCT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCARF"."PRODUCT_TRG" 
BEFORE INSERT ON PRODUCT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.PRODUCT_ID IS NULL THEN
      SELECT PRODUCT_SEQ2.NEXTVAL INTO :NEW.PRODUCT_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "SCARF"."PRODUCT_TRG" ENABLE;
